defmodule Framework.Repo.TenantMigrations.Init4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:inventory_lots, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :lot_code, :text, null: false
      add :expiry_date, :date
      add :received_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :material_id, :uuid, null: false
      add :supplier_id, :uuid
    end

    create index(:inventory_lots, [:supplier_id], name: "inventory_lots_supplier_id_index")

    create index(:inventory_lots, [:material_id], name: "inventory_lots_material_id_index")

    create index(:inventory_lots, [:lot_code],
             name: "inventory_lots_lot_code_index",
             unique: true
           )

    create table(:inventory_material_allergen, primary_key: false, prefix: prefix()) do
      add :material_id, :uuid, null: false, primary_key: true
      add :allergen_id, :uuid, null: false, primary_key: true
    end

    create table(:orders_orders, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :currency, :text, null: false, default: "USD"
      add :reference, :text, null: false
      add :delivery_date, :utc_datetime, null: false
      add :invoice_number, :text
      add :invoice_status, :text, null: false, default: "none"
      add :invoiced_at, :utc_datetime
      add :payment_method, :text
      add :discount_type, :text, null: false, default: "none"
      add :discount_value, :decimal, null: false, default: "0"
      add :delivery_method, :text, null: false, default: "delivery"
      add :status, :text, null: false, default: "unconfirmed"
      add :payment_status, :text, null: false, default: "pending"
      add :subtotal, :decimal, null: false, default: "0"
      add :tax_total, :decimal, null: false, default: "0"
      add :shipping_total, :decimal, null: false, default: "0"
      add :discount_total, :decimal, null: false, default: "0"
      add :total, :decimal, null: false, default: "0"
      add :paid_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id, :uuid, null: false
    end

    create table(:orders_production_batches, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :batch_code, :text, null: false
      add :planned_qty, :decimal, null: false, default: "0"
      add :produced_qty, :decimal, null: false, default: "0"
      add :scrap_qty, :decimal, null: false, default: "0"
      add :status, :text, null: false, default: "open"
      add :notes, :text
      add :bom_version, :bigint
      add :components_map, :map, null: false, default: %{}
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :item_id, :uuid, null: false
      add :bom_id, :uuid
    end

    create index(:orders_production_batches, [:batch_code],
             name: "orders_production_batches_batch_code_index",
             unique: true
           )

    create table(:orders_item_lots, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity_used, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :order_item_id, :uuid, null: false
      add :lot_id, :uuid, null: false
    end

    create table(:inventory_material_nutritional_fact, primary_key: false, prefix: prefix()) do
      add :amount, :decimal, null: false
      add :unit, :text, null: false
      add :material_id, :uuid, null: false, primary_key: true
      add :nutritional_fact_id, :uuid, null: false, primary_key: true
    end

    create table(:inventory_purchase_orders, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :reference, :text, null: false
      add :status, :text, null: false, default: "draft"
      add :ordered_at, :utc_datetime
      add :received_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :supplier_id, :uuid, null: false
    end

    create table(:project_labor_steps, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :sequence, :bigint, null: false, default: 0
      add :duration_minutes, :decimal, null: false, default: "0"
      add :rate_override, :decimal
      add :units_per_run, :decimal, null: false, default: "1"
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bom_id, :uuid, null: false
    end

    create table(:orders_item_batch_allocations, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :planned_qty, :decimal, null: false, default: "0"
      add :completed_qty, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :production_batch_id,
          references(:orders_production_batches,
            column: :id,
            name: "orders_item_batch_allocations_production_batch_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :order_item_id, :uuid, null: false
    end

    create index(:orders_item_batch_allocations, [:production_batch_id],
             name: "orders_item_batch_allocations_batch_idx"
           )

    create index(:orders_item_batch_allocations, [:order_item_id],
             name: "orders_item_batch_allocations_item_idx"
           )

    create index(:orders_item_batch_allocations, [:production_batch_id, :order_item_id],
             name: "orders_item_batch_allocations_unique_pair",
             unique: true
           )

    create table(:inventory_suppliers, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:inventory_purchase_orders, prefix: prefix()) do
      modify :supplier_id,
             references(:inventory_suppliers,
               column: :id,
               name: "inventory_purchase_orders_supplier_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    create unique_index(:inventory_purchase_orders, [:reference],
             name: "inventory_purchase_orders_reference_index"
           )

    alter table(:inventory_suppliers, prefix: prefix()) do
      add :name, :text, null: false
      add :contact_name, :text
      add :contact_email, :text
      add :contact_phone, :text
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:inventory_purchase_order_items, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :decimal, null: false, default: "0"
      add :unit_price, :decimal

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :purchase_order_id,
          references(:inventory_purchase_orders,
            column: :id,
            name: "inventory_purchase_order_items_purchase_order_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :material_id, :uuid, null: false
    end

    create table(:orders_production_batch_lots, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity_used, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :production_batch_id,
          references(:orders_production_batches,
            column: :id,
            name: "orders_production_batch_lots_production_batch_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :lot_id,
          references(:inventory_lots,
            column: :id,
            name: "orders_production_batch_lots_lot_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false
    end

    create index(:orders_production_batch_lots, [:lot_id],
             name: "orders_production_batch_lots_lot_idx"
           )

    create index(:orders_production_batch_lots, [:production_batch_id],
             name: "orders_production_batch_lots_batch_idx"
           )

    create table(:project_bom_rollups, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :material_cost, :decimal, null: false, default: "0"
      add :labor_cost, :decimal, null: false, default: "0"
      add :overhead_cost, :decimal, null: false, default: "0"
      add :unit_cost, :decimal, null: false, default: "0"
      add :components_map, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bom_id, :uuid, null: false
      add :item_id, :uuid, null: false
    end

    create table(:inventory_materials, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:inventory_lots, prefix: prefix()) do
      modify :material_id,
             references(:inventory_materials,
               column: :id,
               name: "inventory_lots_material_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :supplier_id,
             references(:inventory_suppliers,
               column: :id,
               name: "inventory_lots_supplier_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:inventory_material_allergen, prefix: prefix()) do
      modify :material_id,
             references(:inventory_materials,
               column: :id,
               name: "inventory_material_allergen_material_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:inventory_material_nutritional_fact, prefix: prefix()) do
      modify :material_id,
             references(:inventory_materials,
               column: :id,
               name: "inventory_material_nutritional_fact_material_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:inventory_purchase_order_items, prefix: prefix()) do
      modify :material_id,
             references(:inventory_materials,
               column: :id,
               name: "inventory_purchase_order_items_material_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:inventory_materials, prefix: prefix()) do
      add :name, :text, null: false
      add :sku, :text, null: false
      add :unit, :text, null: false
      add :price, :decimal, null: false
      add :minimum_stock, :decimal
      add :maximum_stock, :decimal

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:inventory_materials, [:name], name: "inventory_materials_name_index")

    create unique_index(:inventory_materials, [:sku], name: "inventory_materials_sku_index")

    create table(:orders_items, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:orders_item_lots, prefix: prefix()) do
      modify :order_item_id,
             references(:orders_items,
               column: :id,
               name: "orders_item_lots_order_item_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :lot_id,
             references(:inventory_lots,
               column: :id,
               name: "orders_item_lots_lot_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:orders_item_batch_allocations, prefix: prefix()) do
      modify :order_item_id,
             references(:orders_items,
               column: :id,
               name: "orders_item_batch_allocations_order_item_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:orders_items, prefix: prefix()) do
      add :unit_price, :decimal, null: false
      add :quantity, :decimal, null: false
      add :status, :text, null: false, default: "todo"
      add :consumed_at, :utc_datetime
      add :batch_code, :text
      add :material_cost, :decimal, null: false, default: "0"
      add :labor_cost, :decimal, null: false, default: "0"
      add :overhead_cost, :decimal, null: false, default: "0"
      add :unit_cost, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :order_id,
          references(:orders_orders,
            column: :id,
            name: "orders_items_order_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :item_id, :uuid, null: false
      add :bom_id, :uuid
      add :production_batch_id, :uuid
    end

    create table(:project_boms, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:project_labor_steps, prefix: prefix()) do
      modify :bom_id,
             references(:project_boms,
               column: :id,
               name: "project_labor_steps_bom_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:project_bom_rollups, prefix: prefix()) do
      modify :bom_id,
             references(:project_boms,
               column: :id,
               name: "project_bom_rollups_bom_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:project_boms, prefix: prefix()) do
      add :name, :text
      add :notes, :text
      add :status, :text, null: false, default: "draft"
      add :version, :bigint, null: false
      add :published_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :item_id, :uuid, null: false
    end

    create index(:project_boms, [:item_id],
             name: "project_boms_one_active_per_item",
             unique: true,
             where: "status = 'active'"
           )

    create table(:project_bom_components, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :component_type, :text, null: false, default: "material"
      add :quantity, :decimal, null: false, default: "0"
      add :position, :bigint, null: false, default: 0
      add :waste_percent, :decimal, null: false, default: "0"
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bom_id,
          references(:project_boms,
            column: :id,
            name: "project_bom_components_bom_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :material_id,
          references(:inventory_materials,
            column: :id,
            name: "project_bom_components_material_id_fkey",
            type: :uuid,
            prefix: prefix()
          )

      add :item_id, :uuid
    end

    create table(:inventory_nutritional_facts, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:inventory_material_nutritional_fact, prefix: prefix()) do
      modify :nutritional_fact_id,
             references(:inventory_nutritional_facts,
               column: :id,
               name: "inventory_material_nutritional_fact_nutritional_fact_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:inventory_nutritional_facts, prefix: prefix()) do
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:inventory_nutritional_facts, [:name],
             name: "inventory_nutritional_facts_name_index"
           )

    create table(:inventory_movements, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :decimal, null: false
      add :reason, :text
      add :occurred_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :material_id,
          references(:inventory_materials,
            column: :id,
            name: "inventory_movements_material_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false

      add :lot_id,
          references(:inventory_lots,
            column: :id,
            name: "inventory_movements_lot_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end

    create table(:inventory_allergens, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:inventory_material_allergen, prefix: prefix()) do
      modify :allergen_id,
             references(:inventory_allergens,
               column: :id,
               name: "inventory_material_allergen_allergen_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:inventory_allergens, prefix: prefix()) do
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:inventory_allergens, [:name], name: "inventory_allergens_name_index")

    create table(:project_items, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:orders_production_batches, prefix: prefix()) do
      modify :item_id,
             references(:project_items,
               column: :id,
               name: "orders_production_batches_item_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :bom_id,
             references(:project_boms,
               column: :id,
               name: "orders_production_batches_bom_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:project_bom_rollups, prefix: prefix()) do
      modify :item_id,
             references(:project_items,
               column: :id,
               name: "project_bom_rollups_item_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    create unique_index(:project_bom_rollups, [:bom_id],
             name: "project_bom_rollups_unique_bom_index"
           )

    alter table(:orders_items, prefix: prefix()) do
      modify :item_id,
             references(:project_items,
               column: :id,
               name: "orders_items_item_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :bom_id,
             references(:project_boms,
               column: :id,
               name: "orders_items_bom_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :production_batch_id,
             references(:orders_production_batches,
               column: :id,
               name: "orders_items_production_batch_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:project_boms, prefix: prefix()) do
      modify :item_id,
             references(:project_items,
               column: :id,
               name: "project_boms_item_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    create unique_index(:project_boms, [:item_id, :version],
             name: "project_boms_item_version_index"
           )

    alter table(:project_bom_components, prefix: prefix()) do
      modify :item_id,
             references(:project_items,
               column: :id,
               name: "project_bom_components_item_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:project_items, prefix: prefix()) do
      add :name, :text, null: false
      add :status, :text, null: false, default: "draft"
      add :price, :decimal, null: false
      add :sku, :text, null: false
      add :photos, {:array, :text}, default: []
      add :featured_photo, :text
      add :selling_availability, :text, null: false, default: "available"
      add :max_daily_quantity, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:project_items, [:name], name: "project_items_name_index")

    create unique_index(:project_items, [:sku], name: "project_items_sku_index")

    create table(:crm_customers, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:orders_orders, prefix: prefix()) do
      modify :customer_id,
             references(:crm_customers,
               column: :id,
               name: "orders_orders_customer_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    create unique_index(:orders_orders, [:reference], name: "orders_orders_reference_index")

    alter table(:crm_customers, prefix: prefix()) do
      add :reference, :text, null: false
      add :type, :text, null: false
      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :email, :text
      add :phone, :text
      add :billing_address, :map
      add :shipping_address, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:crm_customers, [:email], name: "crm_customers_email_index")

    create unique_index(:crm_customers, [:phone], name: "crm_customers_phone_index")

    create unique_index(:crm_customers, [:reference], name: "crm_customers_reference_index")
  end

  def down do
    drop_if_exists unique_index(:crm_customers, [:reference],
                     name: "crm_customers_reference_index"
                   )

    drop_if_exists unique_index(:crm_customers, [:phone], name: "crm_customers_phone_index")

    drop_if_exists unique_index(:crm_customers, [:email], name: "crm_customers_email_index")

    alter table(:crm_customers, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :shipping_address
      remove :billing_address
      remove :phone
      remove :email
      remove :last_name
      remove :first_name
      remove :type
      remove :reference
    end

    drop_if_exists unique_index(:orders_orders, [:reference],
                     name: "orders_orders_reference_index"
                   )

    drop constraint(:orders_orders, "orders_orders_customer_id_fkey")

    alter table(:orders_orders, prefix: prefix()) do
      modify :customer_id, :uuid
    end

    drop table(:crm_customers, prefix: prefix())

    drop_if_exists unique_index(:project_items, [:sku], name: "project_items_sku_index")

    drop_if_exists unique_index(:project_items, [:name], name: "project_items_name_index")

    alter table(:project_items, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :max_daily_quantity
      remove :selling_availability
      remove :featured_photo
      remove :photos
      remove :sku
      remove :price
      remove :status
      remove :name
    end

    drop constraint(:project_bom_components, "project_bom_components_item_id_fkey")

    alter table(:project_bom_components, prefix: prefix()) do
      modify :item_id, :uuid
    end

    drop_if_exists unique_index(:project_boms, [:item_id, :version],
                     name: "project_boms_item_version_index"
                   )

    drop constraint(:project_boms, "project_boms_item_id_fkey")

    alter table(:project_boms, prefix: prefix()) do
      modify :item_id, :uuid
    end

    drop constraint(:orders_items, "orders_items_item_id_fkey")

    drop constraint(:orders_items, "orders_items_bom_id_fkey")

    drop constraint(:orders_items, "orders_items_production_batch_id_fkey")

    alter table(:orders_items, prefix: prefix()) do
      modify :production_batch_id, :uuid
      modify :bom_id, :uuid
      modify :item_id, :uuid
    end

    drop_if_exists unique_index(:project_bom_rollups, [:bom_id],
                     name: "project_bom_rollups_unique_bom_index"
                   )

    drop constraint(:project_bom_rollups, "project_bom_rollups_item_id_fkey")

    alter table(:project_bom_rollups, prefix: prefix()) do
      modify :item_id, :uuid
    end

    drop constraint(:orders_production_batches, "orders_production_batches_item_id_fkey")

    drop constraint(:orders_production_batches, "orders_production_batches_bom_id_fkey")

    alter table(:orders_production_batches, prefix: prefix()) do
      modify :bom_id, :uuid
      modify :item_id, :uuid
    end

    drop table(:project_items, prefix: prefix())

    drop_if_exists unique_index(:inventory_allergens, [:name],
                     name: "inventory_allergens_name_index"
                   )

    alter table(:inventory_allergens, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop constraint(:inventory_material_allergen, "inventory_material_allergen_allergen_id_fkey")

    alter table(:inventory_material_allergen, prefix: prefix()) do
      modify :allergen_id, :uuid
    end

    drop table(:inventory_allergens, prefix: prefix())

    drop constraint(:inventory_movements, "inventory_movements_material_id_fkey")

    drop constraint(:inventory_movements, "inventory_movements_lot_id_fkey")

    drop table(:inventory_movements, prefix: prefix())

    drop_if_exists unique_index(:inventory_nutritional_facts, [:name],
                     name: "inventory_nutritional_facts_name_index"
                   )

    alter table(:inventory_nutritional_facts, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop constraint(
           :inventory_material_nutritional_fact,
           "inventory_material_nutritional_fact_nutritional_fact_id_fkey"
         )

    alter table(:inventory_material_nutritional_fact, prefix: prefix()) do
      modify :nutritional_fact_id, :uuid
    end

    drop table(:inventory_nutritional_facts, prefix: prefix())

    drop constraint(:project_bom_components, "project_bom_components_bom_id_fkey")

    drop constraint(:project_bom_components, "project_bom_components_material_id_fkey")

    drop table(:project_bom_components, prefix: prefix())

    drop_if_exists index(:project_boms, [:item_id], name: "project_boms_one_active_per_item")

    alter table(:project_boms, prefix: prefix()) do
      remove :item_id
      remove :updated_at
      remove :inserted_at
      remove :published_at
      remove :version
      remove :status
      remove :notes
      remove :name
    end

    drop constraint(:project_bom_rollups, "project_bom_rollups_bom_id_fkey")

    alter table(:project_bom_rollups, prefix: prefix()) do
      modify :bom_id, :uuid
    end

    drop constraint(:project_labor_steps, "project_labor_steps_bom_id_fkey")

    alter table(:project_labor_steps, prefix: prefix()) do
      modify :bom_id, :uuid
    end

    drop table(:project_boms, prefix: prefix())

    drop constraint(:orders_items, "orders_items_order_id_fkey")

    alter table(:orders_items, prefix: prefix()) do
      remove :production_batch_id
      remove :bom_id
      remove :item_id
      remove :order_id
      remove :updated_at
      remove :inserted_at
      remove :unit_cost
      remove :overhead_cost
      remove :labor_cost
      remove :material_cost
      remove :batch_code
      remove :consumed_at
      remove :status
      remove :quantity
      remove :unit_price
    end

    drop constraint(
           :orders_item_batch_allocations,
           "orders_item_batch_allocations_order_item_id_fkey"
         )

    alter table(:orders_item_batch_allocations, prefix: prefix()) do
      modify :order_item_id, :uuid
    end

    drop constraint(:orders_item_lots, "orders_item_lots_order_item_id_fkey")

    drop constraint(:orders_item_lots, "orders_item_lots_lot_id_fkey")

    alter table(:orders_item_lots, prefix: prefix()) do
      modify :lot_id, :uuid
      modify :order_item_id, :uuid
    end

    drop table(:orders_items, prefix: prefix())

    drop_if_exists unique_index(:inventory_materials, [:sku],
                     name: "inventory_materials_sku_index"
                   )

    drop_if_exists unique_index(:inventory_materials, [:name],
                     name: "inventory_materials_name_index"
                   )

    alter table(:inventory_materials, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :maximum_stock
      remove :minimum_stock
      remove :price
      remove :unit
      remove :sku
      remove :name
    end

    drop constraint(
           :inventory_purchase_order_items,
           "inventory_purchase_order_items_material_id_fkey"
         )

    alter table(:inventory_purchase_order_items, prefix: prefix()) do
      modify :material_id, :uuid
    end

    drop constraint(
           :inventory_material_nutritional_fact,
           "inventory_material_nutritional_fact_material_id_fkey"
         )

    alter table(:inventory_material_nutritional_fact, prefix: prefix()) do
      modify :material_id, :uuid
    end

    drop constraint(:inventory_material_allergen, "inventory_material_allergen_material_id_fkey")

    alter table(:inventory_material_allergen, prefix: prefix()) do
      modify :material_id, :uuid
    end

    drop constraint(:inventory_lots, "inventory_lots_material_id_fkey")

    drop constraint(:inventory_lots, "inventory_lots_supplier_id_fkey")

    alter table(:inventory_lots, prefix: prefix()) do
      modify :supplier_id, :uuid
      modify :material_id, :uuid
    end

    drop table(:inventory_materials, prefix: prefix())

    drop table(:project_bom_rollups, prefix: prefix())

    drop constraint(
           :orders_production_batch_lots,
           "orders_production_batch_lots_production_batch_id_fkey"
         )

    drop constraint(:orders_production_batch_lots, "orders_production_batch_lots_lot_id_fkey")

    drop_if_exists index(:orders_production_batch_lots, [:production_batch_id],
                     name: "orders_production_batch_lots_batch_idx"
                   )

    drop_if_exists index(:orders_production_batch_lots, [:lot_id],
                     name: "orders_production_batch_lots_lot_idx"
                   )

    drop table(:orders_production_batch_lots, prefix: prefix())

    drop constraint(
           :inventory_purchase_order_items,
           "inventory_purchase_order_items_purchase_order_id_fkey"
         )

    drop table(:inventory_purchase_order_items, prefix: prefix())

    alter table(:inventory_suppliers, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :notes
      remove :contact_phone
      remove :contact_email
      remove :contact_name
      remove :name
    end

    drop_if_exists unique_index(:inventory_purchase_orders, [:reference],
                     name: "inventory_purchase_orders_reference_index"
                   )

    drop constraint(:inventory_purchase_orders, "inventory_purchase_orders_supplier_id_fkey")

    alter table(:inventory_purchase_orders, prefix: prefix()) do
      modify :supplier_id, :uuid
    end

    drop table(:inventory_suppliers, prefix: prefix())

    drop constraint(
           :orders_item_batch_allocations,
           "orders_item_batch_allocations_production_batch_id_fkey"
         )

    drop_if_exists index(:orders_item_batch_allocations, [:production_batch_id, :order_item_id],
                     name: "orders_item_batch_allocations_unique_pair"
                   )

    drop_if_exists index(:orders_item_batch_allocations, [:order_item_id],
                     name: "orders_item_batch_allocations_item_idx"
                   )

    drop_if_exists index(:orders_item_batch_allocations, [:production_batch_id],
                     name: "orders_item_batch_allocations_batch_idx"
                   )

    drop table(:orders_item_batch_allocations, prefix: prefix())

    drop table(:project_labor_steps, prefix: prefix())

    drop table(:inventory_purchase_orders, prefix: prefix())

    drop table(:inventory_material_nutritional_fact, prefix: prefix())

    drop table(:orders_item_lots, prefix: prefix())

    drop_if_exists index(:orders_production_batches, [:batch_code],
                     name: "orders_production_batches_batch_code_index"
                   )

    drop table(:orders_production_batches, prefix: prefix())

    drop table(:orders_orders, prefix: prefix())

    drop table(:inventory_material_allergen, prefix: prefix())

    drop_if_exists index(:inventory_lots, [:lot_code], name: "inventory_lots_lot_code_index")

    drop_if_exists index(:inventory_lots, [:material_id],
                     name: "inventory_lots_material_id_index"
                   )

    drop_if_exists index(:inventory_lots, [:supplier_id],
                     name: "inventory_lots_supplier_id_index"
                   )

    drop table(:inventory_lots, prefix: prefix())
  end
end
