defmodule Framework.Repo.TenantMigrations.Init do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_notifications, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sender_user_id, :uuid

      add :recipient_user_id,
          references(:users,
            column: :id,
            name: "user_notifications_recipient_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :subject, :text, null: false
      add :body, :text, null: false
      add :read_at, :utc_datetime
      add :status, :text, null: false, default: "unread"
      add :processed, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:user_groups, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id, :uuid, null: false
      add :user_id, :uuid, null: false
    end

    create table(:tags, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:invitations, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :token, :text, null: false
      add :tenant, :text, null: false
      add :expires_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id, :uuid, null: false
      add :inviter_user_id, :uuid, null: false
      add :invitee_user_id, :uuid
    end

    create table(:groups, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:user_groups, prefix: prefix()) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "user_groups_group_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "user_groups_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:user_groups, [:group_id, :user_id],
             name: "user_groups_unique_name_index"
           )

    alter table(:invitations, prefix: prefix()) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "invitations_group_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :inviter_user_id,
             references(:users,
               column: :id,
               name: "invitations_inviter_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :invitee_user_id,
             references(:users,
               column: :id,
               name: "invitations_invitee_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:groups, prefix: prefix()) do
      add :name, :text, null: false
      add :description, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:groups, [:name], name: "groups_unique_name_index")

    create table(:group_permissions, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :action, :text, null: false
      add :resource, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id,
          references(:groups,
            column: :id,
            name: "group_permissions_group_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false
    end

    create unique_index(:group_permissions, [:group_id, :resource, :action],
             name: "group_permissions_unique_group_permission_index"
           )

    create table(:comments, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :content, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :article_id, :uuid, null: false
      add :parent_id, :uuid, null: false
    end

    create table(:categories, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text
      add :description, :text
      add :parent_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:articles, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:comments, prefix: prefix()) do
      modify :article_id,
             references(:articles,
               column: :id,
               name: "comments_article_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :parent_id,
             references(:comments,
               column: :id,
               name: "comments_parent_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:articles, prefix: prefix()) do
      add :title, :text, null: false
      add :slug, :text
      add :content, :text
      add :views_count, :bigint, default: 0
      add :published, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :category_id,
          references(:categories,
            column: :id,
            name: "articles_category_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :nilify_all
          )
    end

    create table(:article_tags, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :article_id,
          references(:articles,
            column: :id,
            name: "article_tags_article_id_fkey",
            type: :uuid,
            prefix: prefix()
          )

      add :tag_id,
          references(:tags,
            column: :id,
            name: "article_tags_tag_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end

    create unique_index(:article_tags, [:article_id, :tag_id],
             name: "article_tags_unique_article_tag_index"
           )

    create table(:article_feedbacks, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :helpful, :boolean, default: false
      add :feedback, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :article_id,
          references(:articles,
            column: :id,
            name: "article_feedbacks_article_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false
    end
  end

  def down do
    drop constraint(:article_feedbacks, "article_feedbacks_article_id_fkey")

    drop table(:article_feedbacks, prefix: prefix())

    drop_if_exists unique_index(:article_tags, [:article_id, :tag_id],
                     name: "article_tags_unique_article_tag_index"
                   )

    drop constraint(:article_tags, "article_tags_article_id_fkey")

    drop constraint(:article_tags, "article_tags_tag_id_fkey")

    drop table(:article_tags, prefix: prefix())

    drop constraint(:articles, "articles_category_id_fkey")

    alter table(:articles, prefix: prefix()) do
      remove :category_id
      remove :updated_at
      remove :inserted_at
      remove :published
      remove :views_count
      remove :content
      remove :slug
      remove :title
    end

    drop constraint(:comments, "comments_article_id_fkey")

    drop constraint(:comments, "comments_parent_id_fkey")

    alter table(:comments, prefix: prefix()) do
      modify :parent_id, :uuid
      modify :article_id, :uuid
    end

    drop table(:articles, prefix: prefix())

    drop table(:categories, prefix: prefix())

    drop table(:comments, prefix: prefix())

    drop_if_exists unique_index(:group_permissions, [:group_id, :resource, :action],
                     name: "group_permissions_unique_group_permission_index"
                   )

    drop constraint(:group_permissions, "group_permissions_group_id_fkey")

    drop table(:group_permissions, prefix: prefix())

    drop_if_exists unique_index(:groups, [:name], name: "groups_unique_name_index")

    alter table(:groups, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :name
    end

    drop constraint(:invitations, "invitations_group_id_fkey")

    drop constraint(:invitations, "invitations_inviter_user_id_fkey")

    drop constraint(:invitations, "invitations_invitee_user_id_fkey")

    alter table(:invitations, prefix: prefix()) do
      modify :invitee_user_id, :uuid
      modify :inviter_user_id, :uuid
      modify :group_id, :uuid
    end

    drop_if_exists unique_index(:user_groups, [:group_id, :user_id],
                     name: "user_groups_unique_name_index"
                   )

    drop constraint(:user_groups, "user_groups_group_id_fkey")

    drop constraint(:user_groups, "user_groups_user_id_fkey")

    alter table(:user_groups, prefix: prefix()) do
      modify :user_id, :uuid
      modify :group_id, :uuid
    end

    drop table(:groups, prefix: prefix())

    drop table(:invitations, prefix: prefix())

    drop table(:tags, prefix: prefix())

    drop table(:user_groups, prefix: prefix())

    drop constraint(:user_notifications, "user_notifications_recipient_user_id_fkey")

    drop table(:user_notifications, prefix: prefix())
  end
end
