defmodule Framework.Repo.Migrations.Init4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:domains, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :host, :text, null: false
      add :auth_code, :text, null: false
      add :status, :text, null: false
      add :attempts, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "domains_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:domains, [:tenant_id, :host], name: "domains_unique_name_index")

    create table(:accounts_api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :prefix, :text, null: false
      add :key_hash, :text, null: false
      add :scopes, :map, null: false, default: %{}
      add :last_used_at, :utc_datetime
      add :revoked_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "accounts_api_keys_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:accounts_api_keys, [:key_hash], name: "accounts_api_keys_key_hash_index")
  end

  def down do
    drop_if_exists unique_index(:accounts_api_keys, [:key_hash],
                     name: "accounts_api_keys_key_hash_index"
                   )

    drop constraint(:accounts_api_keys, "accounts_api_keys_user_id_fkey")

    drop table(:accounts_api_keys)

    drop_if_exists unique_index(:domains, [:tenant_id, :host], name: "domains_unique_name_index")

    drop constraint(:domains, "domains_tenant_id_fkey")

    drop table(:domains)
  end
end
