defmodule Framework.Repo.Migrations.Init do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :confirmed_at, :utc_datetime_usec
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :current_tenant, :text
      add :hashed_password, :text
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:user_tenants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_tenants_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :tenant_id, :uuid
    end

    create table(:tokens, primary_key: false) do
      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:tenants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:user_tenants) do
      modify :tenant_id,
             references(:tenants,
               column: :id,
               name: "user_tenants_tenant_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:user_tenants, [:user_id, :tenant_id],
             name: "user_tenants_unique_article_tag_index"
           )

    alter table(:tenants) do
      add :name, :text, null: false
      add :domain, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "tenants_owner_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:tenants, [:domain], name: "tenants_unique_domain_index")

    create table(:invitations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :token, :text, null: false
      add :tenant, :text, null: false
      add :expires_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id, :uuid, null: false

      add :inviter_user_id,
          references(:users,
            column: :id,
            name: "invitations_inviter_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :invitee_user_id,
          references(:users,
            column: :id,
            name: "invitations_invitee_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:invitations, "invitations_group_id_fkey")

    drop constraint(:invitations, "invitations_inviter_user_id_fkey")

    drop constraint(:invitations, "invitations_invitee_user_id_fkey")

    drop table(:invitations)

    drop_if_exists unique_index(:tenants, [:domain], name: "tenants_unique_domain_index")

    drop constraint(:tenants, "tenants_owner_user_id_fkey")

    alter table(:tenants) do
      remove :owner_user_id
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :domain
      remove :name
    end

    drop_if_exists unique_index(:user_tenants, [:user_id, :tenant_id],
                     name: "user_tenants_unique_article_tag_index"
                   )

    drop constraint(:user_tenants, "user_tenants_tenant_id_fkey")

    alter table(:user_tenants) do
      modify :tenant_id, :uuid
    end

    drop table(:tenants)

    drop table(:tokens)

    drop constraint(:user_tenants, "user_tenants_user_id_fkey")

    drop table(:user_tenants)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
