defmodule Framework.Repo.Migrations.Init1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tenants) do
      add :prefix, :text
    end
  end

  def down do
    alter table(:tenants) do
      remove :prefix
    end
  end
end
