defmodule Framework.Repo.Migrations.Init34 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tenants) do
      modify :domain, :text, null: false
    end

    drop_if_exists unique_index(:tenants, [:prefix], name: "tenants_unique_prefix_index")
  end

  def down do
    create unique_index(:tenants, [:prefix], name: "tenants_unique_prefix_index")

    alter table(:tenants) do
      modify :domain, :text, null: true
    end
  end
end
